export const REGISTER_DATA = "REGISTER_DATA"
export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const FETCH_QUESTION_START = 'FETCH_QUESTION_START';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS'
export const FETCH_QUESTION_FAIL = 'FETCH_QUESTION_FAIL'
export const FETCH_QUESTION = 'FETCH_QUESTION'



